on: 
  - push
  - pull_request

jobs:
  stuff:
    name: stuff
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/monorepo-changes
        id: repo-changes
        with: 
          repo-token: ${{secrets.GITHUB_TOKEN}
