on: 
  pull_request:
    branches: main

jobs:
  stuff:
    name: stuff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/monorepo-changes
        with: 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5
      - run: pnpm test --filter "[origin/main]"
